### Add product to wishlist of a user
PUT http://localhost:9003/wishlists/Cat4Life/3
Content-Type: application/json

{
  "id": 5,
  "pseudo": "Cat4Life",
  "productId": 3
}

### Delete product from a user's wishlist
DELETE http://localhost:9003/wishlists/Cat4Life/2

### Read the wishlist of a user
GET http://localhost:9003/wishlists/user/Cat4Life

### Delete a user's wishlist
DELETE http://localhost:9003/wishlists/user/Cat4Life

### Delete a product from all wishlists
DELETE http://localhost:9003/product/1
