### Create user
POST http://localhost:8080/users/jean
Content-Type: application/json

{
  "pseudo": "jean",
  "firstname": "jean",
  "lastname": "dupont"
}

### Delete user
DELETE http://localhost:8080/users/jean

### Create wishlist
PUT http://localhost:8080/wishlists/jean/1